export enum NotificationType {
  BOOKING_REQUEST = 'BOOKING_REQUEST',
  BOOKING_CONFIRMED = 'BOOKING_CONFIRMED',
  BOOKING_CANCELLED = 'BOOKING_CANCELLED',

  VENDOR_APPROVED = 'VENDOR_APPROVED',
  VENDOR_REJECTED = 'VENDOR_REJECTED',

  VENUE_APPROVED = 'VENUE_APPROVED',
  VENUE_REJECTED = 'VENUE_REJECTED',

  PAYMENT_SUCCESS = 'PAYMENT_SUCCESS',
  PAYMENT_FAILED = 'PAYMENT_FAILED',

  EVENT_REMINDER = 'EVENT_REMINDER',
  SYSTEM_ALERT = 'SYSTEM_ALERT',
}
