import { Venue, Vendor, Event } from "@/types";

export const MOCK_VENUES: Venue[] = [
  {
    id: "1",
    name: "Grand Ballroom ITC Grand Chola",
    description: "A luxurious 25,000 sq ft pillar-less ballroom perfect for grand weddings and corporate events. Features world-class amenities and elegant decor.",
    address: "63, Mount Road",
    area: "Guindy",
    city: "Chennai",
    capacity: 2000,
    price: 150000,
    basePrice: 150000,
    priceUnit: "per_day",
    images: ["https://images.unsplash.com/photo-1519167758481-83f550bb49b3?ixlib=rb-4.0.3&auto=format&fit=crop&w=2098&q=80"],
    amenities: ["WiFi", "Valet Parking", "Catering", "AV Equipment", "AC", "Stage", "Lighting"],
    rating: 4.9,
    ownerId: "owner1",
  },
  {
    id: "2",
    name: "Taj Coromandel Banquet Hall",
    description: "Elegant banquet hall in the heart of Chennai, ideal for weddings, receptions, and corporate gatherings with premium services.",
    address: "37, Mahatma Gandhi Road",
    area: "Nungambakkam",
    city: "Chennai",
    capacity: 800,
    price: 85000,
    basePrice: 85000,
    priceUnit: "per_day",
    images: ["https://images.unsplash.com/photo-1517457373958-b7bdd4587205?ixlib=rb-4.0.3&auto=format&fit=crop&w=2098&q=80"],
    amenities: ["WiFi", "Parking", "Catering", "AC", "Decor", "Security"],
    rating: 4.8,
    ownerId: "owner2",
  },
  {
    id: "3",
    name: "Le Royal Méridien Grand Ballroom",
    description: "Sophisticated venue with modern architecture, perfect for high-end weddings and corporate events in OMR IT corridor.",
    address: "1, Velachery Main Road",
    area: "Velachery",
    city: "Chennai",
    capacity: 1200,
    price: 120000,
    basePrice: 120000,
    priceUnit: "per_day",
    images: ["https://images.unsplash.com/photo-1519225421980-715cb0202128?ixlib=rb-4.0.3&auto=format&fit=crop&w=2098&q=80"],
    amenities: ["WiFi", "Valet Parking", "Catering", "AV Equipment", "AC", "Green Room"],
    rating: 4.7,
    ownerId: "owner3",
  },
  {
    id: "4",
    name: "Raintree Hotel Anna Nagar",
    description: "Premium hotel venue with beautiful indoor and outdoor spaces for intimate gatherings and medium-sized events.",
    address: "Anna Bypass Road",
    area: "Anna Nagar West",
    city: "Chennai",
    capacity: 500,
    price: 55000,
    basePrice: 55000,
    priceUnit: "per_day",
    images: ["https://images.unsplash.com/photo-1464366400600-7168b8af003f?ixlib=rb-4.0.3&auto=format&fit=crop&w=2098&q=80"],
    amenities: ["WiFi", "Parking", "Catering", "AC", "Stage"],
    rating: 4.5,
    ownerId: "owner4",
  },
  {
    id: "5",
    name: "The Park Hotel Chennai",
    description: "Contemporary venue with stunning city views, perfect for cocktail parties, engagements, and corporate events.",
    address: "601, Anna Salai",
    area: "Nandanam",
    city: "Chennai",
    capacity: 600,
    price: 70000,
    basePrice: 70000,
    priceUnit: "per_day",
    images: ["https://images.unsplash.com/photo-1519167758481-83f550bb49b3?ixlib=rb-4.0.3&auto=format&fit=crop&w=2098&q=80"],
    amenities: ["WiFi", "Valet Parking", "Bar", "AC", "DJ Setup", "Lighting"],
    rating: 4.6,
    ownerId: "owner5",
  },
  {
    id: "6",
    name: "Mayor Ramanathan Chettiar Hall",
    description: "Spacious government-owned convention center ideal for large social gatherings, weddings, and cultural events.",
    address: "EVR Periyar Salai",
    area: "Vepery",
    city: "Chennai",
    capacity: 1500,
    price: 35000,
    basePrice: 35000,
    priceUnit: "per_day",
    images: ["https://images.unsplash.com/photo-1517457373958-b7bdd4587205?ixlib=rb-4.0.3&auto=format&fit=crop&w=2098&q=80"],
    amenities: ["Parking", "AC", "Stage", "Catering Space", "Security"],
    rating: 4.2,
    ownerId: "owner6",
  },
  {
    id: "7",
    name: "Jawaharlal Nehru Indoor Stadium",
    description: "Massive indoor stadium venue for mega events, concerts, exhibitions, and large-scale weddings.",
    address: "Kotturpuram, Near IIT",
    area: "Kotturpuram",
    city: "Chennai",
    capacity: 8000,
    price: 250000,
    basePrice: 250000,
    priceUnit: "per_day",
    images: ["https://images.unsplash.com/photo-1519167758481-83f550bb49b3?ixlib=rb-4.0.3&auto=format&fit=crop&w=2098&q=80"],
    amenities: ["Parking", "AC", "Stage", "Green Room", "Security", "VIP Lounge"],
    rating: 4.4,
    ownerId: "owner7",
  },
  {
    id: "8",
    name: "Green Path Restaurant & Hall",
    description: "Pure vegetarian venue with multi-cuisine catering, perfect for traditional South Indian weddings and functions.",
    address: "14, Halls Road",
    area: "Kilpauk",
    city: "Chennai",
    capacity: 400,
    price: 40000,
    basePrice: 40000,
    priceUnit: "per_day",
    images: ["https://images.unsplash.com/photo-1464366400600-7168b8af003f?ixlib=rb-4.0.3&auto=format&fit=crop&w=2098&q=80"],
    amenities: ["WiFi", "Parking", "Catering", "AC", "Decor"],
    rating: 4.3,
    ownerId: "owner8",
  },
  {
    id: "9",
    name: "The Leela Palace Chennai",
    description: "Ultra-luxury beachfront venue with breathtaking Bay of Bengal views for exclusive high-end events.",
    address: "Adyar Seaface, MRC Nagar",
    area: "Adyar",
    city: "Chennai",
    capacity: 1000,
    price: 180000,
    basePrice: 180000,
    priceUnit: "per_day",
    images: ["https://images.unsplash.com/photo-1519225421980-715cb0202128?ixlib=rb-4.0.3&auto=format&fit=crop&w=2098&q=80"],
    amenities: ["WiFi", "Valet Parking", "Catering", "AV Equipment", "AC", "Beach Access", "Spa"],
    rating: 4.9,
    ownerId: "owner9",
  },
  {
    id: "10",
    name: "Sathyam Cinemas Convention Center",
    description: "Modern convention center with state-of-the-art facilities for corporate events, product launches, and weddings.",
    address: "8, Royapettah High Road",
    area: "Royapettah",
    city: "Chennai",
    capacity: 700,
    price: 65000,
    basePrice: 65000,
    priceUnit: "per_day",
    images: ["https://images.unsplash.com/photo-1517457373958-b7bdd4587205?ixlib=rb-4.0.3&auto=format&fit=crop&w=2098&q=80"],
    amenities: ["WiFi", "Parking", "AV Equipment", "AC", "Stage", "Lighting", "Sound System"],
    rating: 4.5,
    ownerId: "owner10",
  },
  {
    id: "11",
    name: "Thangam Mahal",
    description: "Traditional Chennai wedding hall with authentic decor and excellent South Indian catering services.",
    address: "156, Luz Church Road",
    area: "Mylapore",
    city: "Chennai",
    capacity: 600,
    price: 45000,
    basePrice: 45000,
    priceUnit: "per_day",
    images: ["https://images.unsplash.com/photo-1519167758481-83f550bb49b3?ixlib=rb-4.0.3&auto=format&fit=crop&w=2098&q=80"],
    amenities: ["Parking", "Catering", "AC", "Decor", "Stage", "Music System"],
    rating: 4.4,
    ownerId: "owner11",
  },
  {
    id: "12",
    name: "Rachna Banquet Hall",
    description: "Affordable and spacious banquet hall in Tambaram for middle-class families and budget-friendly events.",
    address: "GST Road",
    area: "Tambaram West",
    city: "Chennai",
    capacity: 350,
    price: 25000,
    basePrice: 25000,
    priceUnit: "per_day",
    images: ["https://images.unsplash.com/photo-1464366400600-7168b8af003f?ixlib=rb-4.0.3&auto=format&fit=crop&w=2098&q=80"],
    amenities: ["Parking", "Catering", "AC", "Stage"],
    rating: 4.1,
    ownerId: "owner12",
  },
  {
    id: "13",
    name: "The Residency Towers",
    description: "Business hotel venue with elegant banquet facilities, ideal for corporate meetings and social gatherings.",
    address: "15, Boag Road",
    area: "T Nagar",
    city: "Chennai",
    capacity: 450,
    price: 50000,
    basePrice: 50000,
    priceUnit: "per_day",
    images: ["https://images.unsplash.com/photo-1517457373958-b7bdd4587205?ixlib=rb-4.0.3&auto=format&fit=crop&w=2098&q=80"],
    amenities: ["WiFi", "Parking", "Catering", "AC", "Projector", "Conference Setup"],
    rating: 4.4,
    ownerId: "owner13",
  },
  {
    id: "14",
    name: "Aavin Bhavan",
    description: "Budget-friendly government-run venue with pure vegetarian catering, perfect for small family functions.",
    address: "1, Rajaji Salai",
    area: "Parrys",
    city: "Chennai",
    capacity: 200,
    price: 15000,
    basePrice: 15000,
    priceUnit: "per_day",
    images: ["https://images.unsplash.com/photo-1464366400600-7168b8af003f?ixlib=rb-4.0.3&auto=format&fit=crop&w=2098&q=80"],
    amenities: ["Parking", "Catering", "AC", "Basic Sound System"],
    rating: 3.9,
    ownerId: "owner14",
  },
  {
    id: "15",
    name: "Crowne Plaza Chennai Adyar Park",
    description: "Upscale hotel with beautiful outdoor lawn and indoor banquet for premium weddings and corporate events.",
    address: "132, Rajiv Gandhi Salai",
    area: "Adyar",
    city: "Chennai",
    capacity: 900,
    price: 95000,
    basePrice: 95000,
    priceUnit: "per_day",
    images: ["https://images.unsplash.com/photo-1519225421980-715cb0202128?ixlib=rb-4.0.3&auto=format&fit=crop&w=2098&q=80"],
    amenities: ["WiFi", "Valet Parking", "Catering", "AV Equipment", "AC", "Outdoor Lawn", "Spa"],
    rating: 4.7,
    ownerId: "owner15",
  },
  {
    id: "16",
    name: "Chettinad Mansion",
    description: "Heritage Chettinad-style mansion with traditional architecture, perfect for cultural weddings and receptions.",
    address: "Palace Road",
    area: "Chettinad",
    city: "Chennai",
    capacity: 400,
    price: 75000,
    basePrice: 75000,
    priceUnit: "per_day",
    images: ["https://images.unsplash.com/photo-1519167758481-83f550bb49b3?ixlib=rb-4.0.3&auto=format&fit=crop&w=2098&q=80"],
    amenities: ["Parking", "Catering", "AC", "Heritage Decor", "Garden"],
    rating: 4.6,
    ownerId: "owner16",
  },
  {
    id: "17",
    name: "SPIC Convention Center",
    description: "Large convention center with modern facilities for corporate events, exhibitions, and trade shows.",
    address: "Kathipara Junction",
    area: "Guindy",
    city: "Chennai",
    capacity: 2500,
    price: 100000,
    basePrice: 100000,
    priceUnit: "per_day",
    images: ["https://images.unsplash.com/photo-1517457373958-b7bdd4587205?ixlib=rb-4.0.3&auto=format&fit=crop&w=2098&q=80"],
    amenities: ["WiFi", "Parking", "AV Equipment", "AC", "Exhibition Space", "Food Court"],
    rating: 4.3,
    ownerId: "owner17",
  },
  {
    id: "18",
    name: "Bharat Nivas Club",
    description: "Exclusive club venue with lakeside setting, ideal for premium social gatherings and corporate retreats.",
    address: "Besant Nagar Beach Road",
    area: "Besant Nagar",
    city: "Chennai",
    capacity: 300,
    price: 60000,
    basePrice: 60000,
    priceUnit: "per_day",
    images: ["https://images.unsplash.com/photo-1464366400600-7168b8af003f?ixlib=rb-4.0.3&auto=format&fit=crop&w=2098&q=80"],
    amenities: ["WiFi", "Parking", "Catering", "AC", "Lake View", "Outdoor Space"],
    rating: 4.5,
    ownerId: "owner18",
  },
  {
    id: "19",
    name: "Rameshwaram Cafe & Hall",
    description: "Famous South Indian restaurant with private hall for traditional ceremonies and family functions.",
    address: "16, Gopalakrishna Street",
    area: "T Nagar",
    city: "Chennai",
    capacity: 250,
    price: 30000,
    basePrice: 30000,
    priceUnit: "per_day",
    images: ["https://images.unsplash.com/photo-1519167758481-83f550bb49b3?ixlib=rb-4.0.3&auto=format&fit=crop&w=2098&q=80"],
    amenities: ["Parking", "Catering", "AC", "Traditional Decor"],
    rating: 4.4,
    ownerId: "owner19",
  },
  {
    id: "20",
    name: "VGP Universal Kingdom",
    description: "Amusement park venue with exclusive after-hours booking option for unique themed parties and events.",
    address: "East Coast Road",
    area: "Injambakkam",
    city: "Chennai",
    capacity: 1500,
    price: 200000,
    basePrice: 200000,
    priceUnit: "per_day",
    images: ["https://images.unsplash.com/photo-1519225421980-715cb0202128?ixlib=rb-4.0.3&auto=format&fit=crop&w=2098&q=80"],
    amenities: ["Parking", "Catering", "Rides Access", "Security", "Photography Spots"],
    rating: 4.7,
    ownerId: "owner20",
  },
];

export const MOCK_VENDORS: Vendor[] = [
  {
    id: "1",
    name: "Annapurna Caterers",
    businessName: "Annapurna Caterers",
    description: "Premium South Indian and North Indian catering service with 30+ years of experience. Specializing in traditional Brahmin cuisine and multi-cuisine buffets.",
    serviceType: "Catering",
    city: "Chennai",
    area: "T Nagar",
    priceRange: "₹₹₹",
    basePrice: 25000,
    images: ["https://images.unsplash.com/photo-1555244162-803834f70033?ixlib=rb-4.0.3&auto=format&fit=crop&w=2098&q=80"],
    rating: 4.8,
    ownerId: "vendor1",
    verificationStatus: "verified",
  },
  {
    id: "2",
    name: "LensCraft Studios",
    businessName: "LensCraft Studios",
    description: "Award-winning wedding photography and cinematography team. Specializing in candid photography, drone shots, and same-day edit videos.",
    serviceType: "Photography",
    city: "Chennai",
    area: "Adyar",
    priceRange: "₹₹₹",
    basePrice: 35000,
    images: ["https://images.unsplash.com/photo-1516035069371-29a1b244cc32?ixlib=rb-4.0.3&auto=format&fit=crop&w=2098&q=80"],
    rating: 4.9,
    ownerId: "vendor2",
    verificationStatus: "verified",
  },
  {
    id: "3",
    name: "Floral Dreams Decor",
    businessName: "Floral Dreams Decor",
    description: "Luxury wedding decoration and floral design studio. Creating magical ambiance with fresh flowers, drapes, lighting, and thematic setups.",
    serviceType: "Decoration",
    city: "Chennai",
    area: "Velachery",
    priceRange: "₹₹₹₹",
    basePrice: 75000,
    images: ["https://images.unsplash.com/photo-1519225421980-715cb0202128?ixlib=rb-4.0.3&auto=format&fit=crop&w=2098&q=80"],
    rating: 4.7,
    ownerId: "vendor3",
    verificationStatus: "verified",
  },
  {
    id: "4",
    name: "DJ Akhil Entertainment",
    businessName: "DJ Akhil Entertainment",
    description: "Chennai's top DJ for weddings and corporate events. Live mixing, LED screens, laser lights, and Bollywood/Tamil hits.",
    serviceType: "DJ & Music",
    city: "Chennai",
    area: "Anna Nagar",
    priceRange: "₹₹",
    basePrice: 15000,
    images: ["https://images.unsplash.com/photo-1516280440614-6697288d5d38?ixlib=rb-4.0.3&auto=format&fit=crop&w=2098&q=80"],
    rating: 4.6,
    ownerId: "vendor4",
    verificationStatus: "verified",
  },
  {
    id: "5",
    name: "Glam Squad by Shalini",
    businessName: "Glam Squad by Shalini",
    description: "Professional bridal makeup and hairstyling services. Using premium products like MAC, Bobbi Brown, and Dyson styling tools.",
    serviceType: "Makeup & Hair",
    city: "Chennai",
    area: "Nungambakkam",
    priceRange: "₹₹₹",
    basePrice: 25000,
    images: ["https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?ixlib=rb-4.0.3&auto=format&fit=crop&w=2098&q=80"],
    rating: 4.8,
    ownerId: "vendor5",
    verificationStatus: "verified",
  },
  {
    id: "6",
    name: "Sweet Bites Bakery",
    businessName: "Sweet Bites Bakery",
    description: "Custom wedding cakes, cupcakes, and dessert tables. Specializing in eggless cakes, fondant designs, and themed desserts.",
    serviceType: "Bakery & Desserts",
    city: "Chennai",
    area: "Mylapore",
    priceRange: "₹₹",
    basePrice: 8000,
    images: ["https://images.unsplash.com/photo-1578985545062-69928b1d9587?ixlib=rb-4.0.3&auto=format&fit=crop&w=2098&q=80"],
    rating: 4.5,
    ownerId: "vendor6",
    verificationStatus: "verified",
  },
  {
    id: "7",
    name: "Mehendi by Zainab",
    businessName: "Mehendi by Zainab",
    description: "Intricate bridal mehendi and henna art. Traditional Arabic, Rajasthani, and contemporary designs with natural henna paste.",
    serviceType: "Mehendi Artist",
    city: "Chennai",
    area: "Royapettah",
    priceRange: "₹₹",
    basePrice: 10000,
    images: ["https://images.unsplash.com/photo-1596230672094-9c8a5b6a7b6e?ixlib=rb-4.0.3&auto=format&fit=crop&w=2098&q=80"],
    rating: 4.7,
    ownerId: "vendor7",
    verificationStatus: "verified",
  },
  {
    id: "8",
    name: "Sangeetha Music Band",
    businessName: "Sangeetha Music Band",
    description: "Live band for weddings and sangeet ceremonies. Covering Bollywood, Tamil, Western, and classical fusion performances.",
    serviceType: "Live Band",
    city: "Chennai",
    area: "Kilpauk",
    priceRange: "₹₹₹",
    basePrice: 40000,
    images: ["https://images.unsplash.com/photo-1501612780327-45045538702b?ixlib=rb-4.0.3&auto=format&fit=crop&w=2098&q=80"],
    rating: 4.6,
    ownerId: "vendor8",
    verificationStatus: "verified",
  },
  {
    id: "9",
    name: "Eventz & More",
    businessName: "Eventz & More",
    description: "Full-service event planning and coordination. From intimate gatherings to grand weddings, we handle everything end-to-end.",
    serviceType: "Event Planner",
    city: "Chennai",
    area: "Guindy",
    priceRange: "₹₹₹₹",
    basePrice: 100000,
    images: ["https://images.unsplash.com/photo-1511795409834-ef04bbd61622?ixlib=rb-4.0.3&auto=format&fit=crop&w=2098&q=80"],
    rating: 4.8,
    ownerId: "vendor9",
    verificationStatus: "verified",
  },
  {
    id: "10",
    name: "Traditional Touch Catering",
    businessName: "Traditional Touch Catering",
    description: "Authentic Chettinad and Tamil Brahmin catering served on banana leaves. Specializing in traditional wedding feasts.",
    serviceType: "Catering",
    city: "Chennai",
    area: "Mylapore",
    priceRange: "₹₹",
    basePrice: 18000,
    images: ["https://images.unsplash.com/photo-1555244162-803834f70033?ixlib=rb-4.0.3&auto=format&fit=crop&w=2098&q=80"],
    rating: 4.5,
    ownerId: "vendor10",
    verificationStatus: "verified",
  },
  {
    id: "11",
    name: "Picture Perfect Photography",
    businessName: "Picture Perfect Photography",
    description: "Budget-friendly photography and videography packages. Pre-wedding shoots, candid coverage, and cinematic wedding films.",
    serviceType: "Photography",
    city: "Chennai",
    area: "Tambaram",
    priceRange: "₹",
    basePrice: 12000,
    images: ["https://images.unsplash.com/photo-1516035069371-29a1b244cc32?ixlib=rb-4.0.3&auto=format&fit=crop&w=2098&q=80"],
    rating: 4.3,
    ownerId: "vendor11",
    verificationStatus: "verified",
  },
  {
    id: "12",
    name: "Royal Decorators",
    businessName: "Royal Decorators",
    description: "Affordable decoration services with creative themes. Backdrop designs, flower arrangements, and stage setups for all budgets.",
    serviceType: "Decoration",
    city: "Chennai",
    area: "Vadapalani",
    priceRange: "₹₹",
    basePrice: 30000,
    images: ["https://images.unsplash.com/photo-1519225421980-715cb0202128?ixlib=rb-4.0.3&auto=format&fit=crop&w=2098&q=80"],
    rating: 4.4,
    ownerId: "vendor12",
    verificationStatus: "verified",
  },
  {
    id: "13",
    name: "BollyWood Beats DJ",
    businessName: "BollyWood Beats DJ",
    description: "High-energy DJ performances with latest Bollywood and Kollywood hits. LED dance floors and smoke machines available.",
    serviceType: "DJ & Music",
    city: "Chennai",
    area: "Porur",
    priceRange: "₹",
    basePrice: 10000,
    images: ["https://images.unsplash.com/photo-1516280440614-6697288d5d38?ixlib=rb-4.0.3&auto=format&fit=crop&w=2098&q=80"],
    rating: 4.4,
    ownerId: "vendor13",
    verificationStatus: "pending",
  },
  {
    id: "14",
    name: "Bridal Glow Studio",
    businessName: "Bridal Glow Studio",
    description: "Complete bridal makeover services including makeup, hair, draping, and pre-bridal skincare consultations.",
    serviceType: "Makeup & Hair",
    city: "Chennai",
    area: "Besant Nagar",
    priceRange: "₹₹",
    basePrice: 20000,
    images: ["https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?ixlib=rb-4.0.3&auto=format&fit=crop&w=2098&q=80"],
    rating: 4.6,
    ownerId: "vendor14",
    verificationStatus: "verified",
  },
  {
    id: "15",
    name: "Cake Couture",
    businessName: "Cake Couture",
    description: "Luxury designer cakes for weddings and engagements. Multi-tier cakes, sugar flowers, and personalized cake toppers.",
    serviceType: "Bakery & Desserts",
    city: "Chennai",
    area: "Alwarpet",
    priceRange: "₹₹₹",
    basePrice: 15000,
    images: ["https://images.unsplash.com/photo-1578985545062-69928b1d9587?ixlib=rb-4.0.3&auto=format&fit=crop&w=2098&q=80"],
    rating: 4.7,
    ownerId: "vendor15",
    verificationStatus: "verified",
  },
  {
    id: "16",
    name: "Rangoli Mehendi Artists",
    businessName: "Rangoli Mehendi Artists",
    description: "Team of experienced mehendi artists for bridal and guest applications. Quick-drying natural henna with dark stain guarantee.",
    serviceType: "Mehendi Artist",
    city: "Chennai",
    area: "Ashok Nagar",
    priceRange: "₹",
    basePrice: 8000,
    images: ["https://images.unsplash.com/photo-1596230672094-9c8a5b6a7b6e?ixlib=rb-4.0.3&auto=format&fit=crop&w=2098&q=80"],
    rating: 4.5,
    ownerId: "vendor16",
    verificationStatus: "verified",
  },
  {
    id: "17",
    name: "Fusion Live Band",
    businessName: "Fusion Live Band",
    description: "Versatile band performing across genres - Carnatic fusion, Bollywood rock, and international pop covers.",
    serviceType: "Live Band",
    city: "Chennai",
    area: "OMR",
    priceRange: "₹₹",
    basePrice: 35000,
    images: ["https://images.unsplash.com/photo-1501612780327-45045538702b?ixlib=rb-4.0.3&auto=format&fit=crop&w=2098&q=80"],
    rating: 4.5,
    ownerId: "vendor17",
    verificationStatus: "verified",
  },
  {
    id: "18",
    name: "Dream Weddings by Priya",
    businessName: "Dream Weddings by Priya",
    description: "Boutique wedding planning service specializing in intimate weddings and destination events in and around Chennai.",
    serviceType: "Event Planner",
    city: "Chennai",
    area: "Boat Club",
    priceRange: "₹₹₹",
    basePrice: 75000,
    images: ["https://images.unsplash.com/photo-1511795409834-ef04bbd61622?ixlib=rb-4.0.3&auto=format&fit=crop&w=2098&q=80"],
    rating: 4.7,
    ownerId: "vendor18",
    verificationStatus: "verified",
  },
  {
    id: "19",
    name: "Spice Garden Catering",
    businessName: "Spice Garden Catering",
    description: "Multi-cuisine catering with live counters. North Indian, Chinese, Continental, and South Indian delicacies.",
    serviceType: "Catering",
    city: "Chennai",
    area: "Sholinganallur",
    priceRange: "₹₹₹",
    basePrice: 30000,
    images: ["https://images.unsplash.com/photo-1555244162-803834f70033?ixlib=rb-4.0.3&auto=format&fit=crop&w=2098&q=80"],
    rating: 4.6,
    ownerId: "vendor19",
    verificationStatus: "verified",
  },
  {
    id: "20",
    name: "Candid Moments Studio",
    businessName: "Candid Moments Studio",
    description: "Storytelling through photography - capturing genuine emotions and unscripted moments on your special day.",
    serviceType: "Photography",
    city: "Chennai",
    area: "Kotturpuram",
    priceRange: "₹₹₹",
    basePrice: 40000,
    images: ["https://images.unsplash.com/photo-1516035069371-29a1b244cc32?ixlib=rb-4.0.3&auto=format&fit=crop&w=2098&q=80"],
    rating: 4.8,
    ownerId: "vendor20",
    verificationStatus: "verified",
  },
];

export const MOCK_EVENTS: Event[] = [
  {
    id: "1",
    customerId: "cust1",
    name: "Priya & Karthik Wedding",
    date: "2024-06-15",
    guestCount: 800,
    city: "Chennai",
    status: "planning",
    vendorIds: ["1", "2", "3"],
    venueId: "1",
    totalCost: 350000,
  },
  {
    id: "2",
    customerId: "cust2",
    name: "TechCorp Annual Meet 2024",
    date: "2024-09-20",
    guestCount: 500,
    city: "Chennai",
    status: "booked",
    venueId: "3",
    vendorIds: ["1", "4", "9"],
    totalCost: 275000,
  },
  {
    id: "3",
    customerId: "cust3",
    name: "Ananya's Engagement",
    date: "2024-05-10",
    guestCount: 300,
    city: "Chennai",
    status: "confirmed",
    venueId: "5",
    vendorIds: ["2", "5", "6", "8"],
    totalCost: 125000,
  },
  {
    id: "4",
    customerId: "cust4",
    name: "Ram Kumar Reception",
    date: "2024-07-22",
    guestCount: 600,
    city: "Chennai",
    status: "planning",
    venueId: "2",
    vendorIds: ["1", "3", "4", "7"],
    totalCost: 195000,
  },
  {
    id: "5",
    customerId: "cust5",
    name: "Lakshmi Birthday Celebration",
    date: "2024-04-18",
    guestCount: 150,
    city: "Chennai",
    status: "confirmed",
    venueId: "4",
    vendorIds: ["6", "13", "14"],
    totalCost: 65000,
  },
];
